# Generated by Django 3.2.6 on 2021-08-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_drinks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='image',
            field=models.ImageField(upload_to='Uploads/'),
        ),
    ]
